import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Navbar from '@/components/navbars/Navbar';
import { Inter } from 'next/font/google';
import '../globals.css';
import '../../styles/user.css';
import { ReduxProvider } from '@/redux/provider';
import { Suspense } from 'react';
import Loading from './loading';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased bg-gray-100 ${inter.className}`}>
        <ReduxProvider>
          <Header />
          <Navbar />
          <Suspense fallback={<Loading />}>{children}</Suspense>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
