import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Navbar from "@/components/navbars/Navbar";
import { Inter } from "next/font/google";
import "../globals.css";
import Aside from "@/components/Aside";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased bg-gray-100 ${inter.className}`}>
        <Header />
        <Navbar />
        <main className="container mx-auto mt-6 px-6">
          <div className="flex flex-col lg:flex-row">
            <div className="w-full lg:w-3/4 lg:pr-6">{children}</div>
            <Aside />
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
